apiVersion: v1
kind: Service
metadata:
  name: sample-api-lb
  namespace: apps-prod
  labels:
    app: sample-api
    exposure: public
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: sample-api
  ports:
    - name: https
      port: 443
      targetPort: 8443
