apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: data-prod
  labels:
    app: kafka
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
